name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev libsqlite3-dev libssl-dev

    - name: make
      run: make
    - name: make check
      run: make check
    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Install at-spi2-core (if necessary)
      run: sudo apt-get install -y at-spi2-core
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &
    - name: Set DISPLAY environment variable
      run: export DISPLAY=:99
    - name: Run UI tests with virtual display
      run: xvfb-run -a ./switcher -d
